---
- hosts: db
  become: true
  tasks:
    - name: Ensure MariaDB-server is installed
      ansible.builtin.package:
        name: mariadb-server
        state: present

    - name: Ensure mariadb service is enabled and started
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true
